FROM openjdk:12-alpine

RUN apk update && apk add libstdc++ bash curl && rm -rf /var/cache/apk/*

# Install Web3j-cli
RUN curl -L https://get.web3j.io | bash

# Install Gradle
ENV GRADLE_VERSION 5.0
ENV GRADLE_HOME /usr/local/gradle
ENV PATH ${PATH}:${GRADLE_HOME}/bin
ENV GRADLE_USER_HOME /gradle

WORKDIR /usr/local
RUN wget  https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip && \
    unzip gradle-$GRADLE_VERSION-bin.zip && \
    rm -f gradle-$GRADLE_VERSION-bin.zip && \
    ln -s gradle-$GRADLE_VERSION gradle && \
    echo -ne "- with Gradle $GRADLE_VERSION\n" >> /root/.built

# Create a test project to download the dependencies
RUN $HOME/.web3j/web3j new -n test -o /tmp -p testp  && rm -rf /tmp/test

ENTRYPOINT ["/root/.web3j/web3j"]
