FROM openjdk:11

# Install Gradle
RUN apt-get update && apt-get install -y gradle curl && rm -rf /var/lib/apt/lists/*

# Install Web3j-cli
RUN curl -L https://get.web3j.io | bash

# Create a test project to download the dependencies
RUN $HOME/.web3j/web3j new -n test -o /tmp -p testp  && rm -rf /tmp/test

ENTRYPOINT ["/root/.web3j/web3j"]
